import markdown
from xhtml2pdf import pisa
import os

class PDFGenerator:
    def __init__(self, output_dir="."):
        self.output_dir = output_dir

    def convert(self, source_html, output_filename="report.pdf"):
        output_path = os.path.join(self.output_dir, output_filename)
        
        # Define basic CSS
        css = """
        <style>
            @page {
                size: a4 portrait;
                @frame header_frame {
                    -pdf-frame-content: header_content;
                    left: 50pt; width: 512pt; top: 50pt; height: 40pt;
                }
                @frame content_frame {
                    left: 50pt; width: 512pt; top: 90pt; height: 632pt;
                }
                @frame footer_frame {
                    -pdf-frame-content: footer_content;
                    left: 50pt; width: 512pt; top: 772pt; height: 20pt;
                }
            }
            body { font-family: Helvetica; font-size: 10pt; }
            h1 { font-size: 24pt; color: #333333; border-bottom: 2px solid #333333; padding-bottom: 5px; }
            h2 { font-size: 18pt; color: #666666; margin-top: 20px; }
            h3 { font-size: 14pt; color: #2E8B57; }
            pre { background-color: #f0f0f0; padding: 10px; border: 1px solid #cccccc; font-family: Courier; white-space: pre-wrap; word-wrap: break-word; }
            code { background-color: #f0f0f0; font-family: Courier; }
            .vulnerability { border: 1px solid #ddd; padding: 10px; margin-bottom: 10px; break-inside: avoid; }
            .high { border-left: 5px solid #ff0000; }
            .medium { border-left: 5px solid #ffa500; }
            .low { border-left: 5px solid #0000ff; }
        </style>
        """

        # Prepare HTML structure
        final_html = f"""
        <html>
        <head>{css}</head>
        <body>
            <div id="header_content">Bug Bounty Hunter Report</div>
            <div id="footer_content">Generated by Bug Bounty Hunter Agent</div>
            {source_html}
        </body>
        </html>
        """

        with open(output_path, "w+b") as out_file:
            pisa_status = pisa.CreatePDF(final_html, dest=out_file)

        return not pisa_status.err

    def generate_from_markdown(self, markdown_content, filename="scan_report.pdf"):
        # Convert MD to HTML
        html_content = markdown.markdown(markdown_content, extensions=['fenced_code', 'tables'])
        return self.convert(html_content, filename)
